In [2]:
import numpy as np 
import pandas as pd

In [3]:
import os
print(os.getcwd())
print(os.listdir())

/home/shreyas-nalle/Desktop/EDA Projects/Titanic_dataset
['train.csv', '.ipynb_checkpoints', 'training_dataset.ipynb']

In [4]:
train_dataset = pd.read_csv("train.csv")
train_dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
heading = train_dataset.head()
heading

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
tail = train_dataset.tail()
tail

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
information = train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
description = train_dataset.describe()
description

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
shape = train_dataset.shape
shape

(891, 12)

In [10]:
print(f"Total passengers on board are {train_dataset.shape[0]}")

Total passengers on board are 891

In [11]:
survived_df = train_dataset[train_dataset["Survived"] == 1]
survived_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [12]:
total_people = train_dataset.shape[0]
print(f"{survived_df.shape[0]} people survived out of {total_people}")

342 people survived out of 891

In [14]:
total_male = (train_dataset["Sex"] == "male").sum()
print(f"Total number of male are {total_male}")
total_female = (train_dataset["Sex"] == "female").sum()
print(f"Total number of female are {total_female}")

Total number of male are 577
Total number of female are 314

In [15]:
male_survived_df = survived_df[survived_df["Sex"] == "male"]
male_survived_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [16]:
female_survived_df = survived_df[survived_df["Sex"] == "female"]
female_survived_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [19]:
print(f"{male_survived_df.shape[0]} male survived out of {total_male}")
print(f"{(total_male) - (male_survived_df.shape[0])} male died")
print("")
print(f"{female_survived_df.shape[0]} female survived out of {total_female}")
print(f"{(total_female) - (female_survived_df.shape[0])} female died")

109 male survived out of 577
468 male died

233 female survived out of 314
81 female died

In [21]:
total_upper_class_male = ((train_dataset["Pclass"] == 1) & (train_dataset["Sex"] == "male")).sum()
print(f"Total number of upper class men are {total_upper_class_male}")
total_middle_class_male = ((train_dataset["Pclass"] == 2) & (train_dataset["Sex"] == "male")).sum()
print(f"Total number of middle class men are {total_middle_class_male}")
total_lower_class_male = ((train_dataset["Pclass"] == 3) & (train_dataset["Sex"] == "male")).sum()
print(f"Total number of lower class men are {total_lower_class_male}")
print("")
total_upper_class_female = ((train_dataset["Pclass"] == 1) & (train_dataset["Sex"] == "female")).sum()
print(f"Total number of upper class men are {total_upper_class_female}")
total_middle_class_female = ((train_dataset["Pclass"] == 2) & (train_dataset["Sex"] == "female")).sum()
print(f"Total number of middle class men are {total_middle_class_female}")
total_lower_class_female = ((train_dataset["Pclass"] == 3) & (train_dataset["Sex"] == "female")).sum()
print(f"Total number of lower class men are {total_lower_class_female}")

Total number of upper class men are 122
Total number of middle class men are 108
Total number of lower class men are 347

Total number of upper class men are 94
Total number of middle class men are 76
Total number of lower class men are 144

In [22]:
total_survived_upper_class_male = (male_survived_df["Pclass"] == 1).sum()
print(f"The total number of upper class male survived are {total_survived_upper_class_male} out of {total_upper_class_male}")
total_survived_middle_class_male = (male_survived_df["Pclass"] == 2).sum()
print(f"The total number of middle class male survived are {total_survived_middle_class_male} out of {total_middle_class_male}")
total_survived_lower_class_male = (male_survived_df["Pclass"] == 3).sum()
print(f"The total number of lower class male survived are {total_survived_lower_class_male} out of {total_lower_class_male}")
print("")
total_survived_upper_class_female = (female_survived_df["Pclass"] == 1).sum()
print(f"The total number of upper class female survived are {total_survived_upper_class_female} out of {total_upper_class_female}")
total_survived_middle_class_female = (female_survived_df["Pclass"] == 2).sum()
print(f"The total number of middle class female survived are {total_survived_middle_class_female} out of {total_middle_class_female}")
total_survived_lower_class_female = (female_survived_df["Pclass"] == 3).sum()
print(f"The total number of lower class female survived are {total_survived_lower_class_female} out of {total_lower_class_female}")

The total number of upper class male survived are 45 out of 122
The total number of middle class male survived are 17 out of 108
The total number of lower class male survived are 47 out of 347

The total number of upper class female survived are 91 out of 94
The total number of middle class female survived are 70 out of 76
The total number of lower class female survived are 72 out of 144

In [23]:
total_male_survived = male_survived_df.shape[0]
percentage_of_male_survived  = (total_male_survived / total_male) * 100
print(f"The percentage of male survived is {percentage_of_male_survived:.4f}")
print("")
total_female_survived = female_survived_df.shape[0]
percentage_of_female_survived = (total_female_survived / total_female) * 100
print(f"The percentage of female survived is {percentage_of_female_survived:.4f}")
print("")
survival_mean_by_sex = train_dataset.groupby("Sex")["Survived"].mean()
print(type(survival_mean_by_sex))
print(f"The mean of male survival is {survival_mean_by_sex['male']:.4f}")
print(f"The mean of the female survival is {survival_mean_by_sex['female']:.4f}")

The percentage of male survived is 18.8908

The percentage of female survived is 74.2038

<class 'pandas.core.series.Series'>
The mean of male survival is 0.1889
The mean of the female survival is 0.7420

In [57]:
print(f"Thus clearly showing that the female survival rate was much greater than the males")

Thus clearly showing that the female survival rate was much greater than the males

In [58]:
class_wise_survival = train_dataset.groupby("Pclass")["Survived"].mean()
total_upper_class_percentage_survival = class_wise_survival[1] * 100
total_middle_class_percentage_survival = class_wise_survival[2] * 100
total_lower_class_percentage_survival = class_wise_survival[3] * 100
print(f"Upper class survival percentage is {total_upper_class_percentage_survival:.4f}")
print(f"Middle class survival percentage is {total_middle_class_percentage_survival:.4f}")
print(f"Lower class survival percentage is {total_lower_class_percentage_survival:.4f}")

Upper class survival percentage is 62.9630
Middle class survival percentage is 47.2826
Lower class survival percentage is 24.2363

In [ ]:
print(f"Thus showing that upper class people were given priority while evacuating")

In [26]:
class_sex_wise_survival = train_dataset.groupby(["Pclass", "Sex"])["Survived"].mean().mul(100).reset_index(name = "Survival_Percentage")
class_sex_wise_survival["Survival_Percentage"] = class_sex_wise_survival["Survival_Percentage"].round(4)
class_sex_wise_survival

   Pclass     Sex  Survival_Percentage
0       1  female              96.8085
1       1    male              36.8852
2       2  female              92.1053
3       2    male              15.7407
4       3  female              50.0000
5       3    male              13.5447

In [59]:
print(type(class_sex_wise_survival))
print("Class wise and sex wise data analaysis done, class wise gender based evaculation was done")

<class 'pandas.core.frame.DataFrame'>
Class wise and sex wise data analaysis done, class wise gender based evaculation was done

In [29]:
survived_df_below18 = survived_df[survived_df["Age"] <= 18]
survived_df_below18

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.00,0,1,392091,9.3500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

In [41]:
below18_survived_percentage = ((survived_df_below18.shape[0]) / ((train_dataset["Age"] <= 18).sum())) * 100
print(f"{survived_df_below18.shape[0]} number of people below the age of 18 survived and the survival percentage of them is {below18_survived_percentage:.4f}")

70 number of people below the age of 18 survived and the survival percentage of them is 50.3597

In [38]:
age18toage50_suvived_df = survived_df[(survived_df["Age"] > 18) & (survived_df["Age"] <= 50)]
age18toage50_suvived_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [51]:
age18toage50_survived_percentage = ( age18toage50_suvived_df.shape[0] / (((train_dataset["Age"] > 18) & (train_dataset["Age"] <= 50)).sum()) ) * 100
print(f"{age18toage50_suvived_df.shape[0]} number of people in between the age of 18 and 50 survived and the survival percentage of them is {age18toage50_survived_percentage:.4f}")

198 number of people in between the age of 18 and 50 survived and the survival percentage of them is 38.7476

In [53]:
ageabove50_survived_df = survived_df[survived_df["Age"] >= 50]
ageabove50_survived_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0000,NaN,S
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
458,459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5000,NaN,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
496,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C
513,514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,1,0,PC 17603,59.4000,NaN,C
526,527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.5000,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
591,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S
774,775,1,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,29105,23.0000,NaN,S
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [55]:
ageabove50_survived_percentage = ((ageabove50_survived_df.shape[0]) / ((train_dataset["Age"] >= 50).sum())) * 100 
print(f"{ageabove50_survived_df.shape[0]} number of people above the age of 50 survived and the survival percentage of them is {ageabove50_survived_percentage:.4f}")

27 number of people above the age of 50 survived and the survival percentage of them is 36.4865

In [56]:
print(f"Evacuation was done quite prominently when it comes to age")

Evacuation was done quite prominently when it comes to age

In [63]:
max_ticket_price = train_dataset["Fare"].max()
print(f"The maximum ticket price was {max_ticket_price}")
min_ticket_price = train_dataset["Fare"].min()
print(f"The maximum ticket price was {min_ticket_price}")

The maximum ticket price was 512.3292
The maximum ticket price was 0.0

In [64]:
number_of_ticket_in_between_0to50 = ((train_dataset["Fare"] >= 0) & (train_dataset["Fare"] < 50)).sum()
print(f"The number of people with the ticket fare in between 0 to 50 dollar is {number_of_ticket_in_between_0to50}")

The number of people with the ticket fair in between 0 to 50 dollar is 730